# Generated by Django 4.2.10 on 2024-02-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_list', '0002_shoppinglist_is_public_shoppinglist_owner_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='owner',
        ),
    ]
