# Generated by Django 4.2.10 on 2024-02-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_list', '0004_shoppinglist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
