# Generated by Django 4.2.10 on 2024-02-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_list', '0006_shoppinglistpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='original_list_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
