# Generated by Django 4.2.10 on 2024-03-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_list', '0007_shoppinglist_original_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='clone_count',
            field=models.IntegerField(default=0),
        ),
    ]
